### ISSUE TITLE
Error during ImportAsync

### ISSUE THREAD

**Issue by GeorgeS2019** [sps014/BlazorBindGen#16]
Just loading this library ALONE trigger error.  Any idea?

```cs

protected override async Task OnInitializedAsync()
{
   await runImport();
}

async Task runImport()
{
   await ImportAsync("	https://cdnjs.cloudflare.com/ajax/libs/jsPlumb/1.7.6/jquery.jsPlumb.min.js");
}
```
```
blazor.webassembly.js:1 
        
       crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: TypeError: Cannot set properties of undefined (setting 'jsBezier')
System.Exception: TypeError: Cannot set properties of undefined (setting 'jsBezier')
   at BlazorBindGen.Bindings.LockHandler.HoldVoid(Int64 errH)
   at BlazorBindGen.BindGen.ImportAsync(String moduleUrl)
   at JsPlumbBlazor.Pages.JsPlumb2.JsPlumbInit() in ---\Pages\JsPlumb2.razor:line 81
   at JsPlumbBlazor.Pages.JsPlumb2.OnInitializedAsync() in ---\Pages\JsPlumb2.razor:line 67
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

**Comment by sps014** [comment]
Looks issue with lib itself , importAsync is js import wrapper  , located here
https://github.com/sps014/BlazorBindGen/blob/e915288eef67954533b381ab9d42726dcfaa3cc3/BlazorBindGen/wwwroot/BlazorBindGen.js#L82

**Comment by GeorgeS2019** [comment]
There is no problem loading this module if I place it below in` index.html`

```html
<script src="_framework/blazor.webassembly.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jsPlumb/1.7.6/jquery.jsPlumb.min.js"></script>
```

**Comment by GeorgeS2019** [comment]
I have no problem import below Except the jsplumb module

```cs
        await ImportAsync("https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.min.js");
        await ImportAsync("https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js");
        //await ImportAsync("https://cdnjs.cloudflare.com/ajax/libs/jsPlumb/1.7.6/jquery.jsPlumb.js");
```

**Comment by sps014** [comment]
You should read what you can import
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import
