### ISSUE TITLE
Why this is not right?

### ISSUE THREAD

**Issue by GeorgeS2019** [sps014/BlazorBindGen#2]
Thx for creating this interesting framework. I was learning through the sample information provided. 

I do not get any error and the expected result. Any suggestion?

[Source Ref](https://blog.js.cytoscape.org/2016/05/24/getting-started/)

```html
<body>
    <div id="cy"></div>
</body>

```

### cytoscape.razor
```cs

@page "/cytoscape1"

@using BlazorBindGen
@using static BlazorBindGen.BindGen
@inject IJSRuntime runtime

<div id="cy" ></div>

@code
{
	JWindow win;
	protected override async Task OnInitializedAsync()
	{
		await base.OnInitializedAsync();
		await Init(runtime);
		win = Window;
		await Draw();
	}
        
        //var cy = cytoscape({
	//container: document.getElementById('cy'),
	//elements: [
	//  { data: { id: 'a' } },
	//  { data: { id: 'b' } },
	//  {
	//    data: {
	//      id: 'ab',
	//       source: 'a',
	//      target: 'b'
	//    }
	//  }]
	//});
	async Task Draw()
	{
		await Import("https://cytoscape.org/cytoscape.js-tutorial-demo/js/cytoscape.min.js");
		var cyCanvas= win.PropRef("document").CallRef("getElementById", "cy");
		JObjPtr _cy = Window.Construct("cytoscape"); /* js reference to cytoscape */ 
		string elements = @"[
							{ data: { id: 'a' } },
							{ data: { id: 'b' } },
							{
							  data: {
								id: 'ab',
								source: 'a',
								target: 'b'
							  }
							}]";
		_cy.SetPropRef("container",cyCanvas); 
		_cy.SetPropVal<string>("elements", elements); 

	}
```
```html
<style>
    #cy {
        width: 100%;
        height: 100%;
        position: absolute;
        top: 0px;
        left: 0px;
    }
</style>
```

### Source for working cytoscape.min.js

[cytoscape.min.js](https://github.com/sps014/BlazorBindGen/files/7394082/cytoscape.min.js.zip)

### expected result
![image](https://user-images.githubusercontent.com/49812372/138388118-e07286ba-d0ce-4534-94a5-10e3ff90803d.png)

**Comment by GeorgeS2019** [comment]
@sps014  => I could not get it to display "RED hexagon"

Any suggestion?


[HTML Source](https://github.com/cytoscape/cytoscape.js-tutorials/blob/master/getting-started/index-layout.html): 

```js

{
          container: document.getElementById('cy'),
          elements: [
            // nodes
            { data: { id: 'a' } },
            { data: { id: 'b' } },
            // edges
            {
              data: {
                id: 'ab',
                source: 'a',
                target: 'b'
              }
            },
          ],
          style: [
            {
              selector: 'node',
              style: {
                shape: 'hexagon',
                'background-color': 'red',
                label: 'data(id)'
              }
            }],
          layout: {
            name: 'grid'
          }
 }
```
```cs
/// Elements
    public class Element
    {
        public Data data { get; set; }
    }

    public class Data
    {
        public string id { get; set; }
        public string source { get; set; }
        public string target { get; set; }
    }

/// Style
    public class Style
    {
       public string selector  { get; set; }
        public StyleElement style { get; set; }
    }

    public class StyleElement
    {
        public string shape{ get; set; }
        public string label{ get; set; }
    }

/// Layout
    public class Layout
    {
        public string name { get; set; }
    }

    public class Root
    {
        public ElementReference container { get; set; }
        public List<Element> elements { get; set; }
        public List<Style> style{ get; set; }
        public Layout layout { get; set; }
    }
```

```
<style>
    #cy {
        width: 400px;
        height: 400px;
        position: relative;
        top: 20px;
        left: 20px;
        border: 3px solid #73AD21;
    }
</style>
```

![image](https://user-images.githubusercontent.com/49812372/184249605-430aa090-48c0-4d54-8d78-7689f29b5a79.png)

**Comment by GeorgeS2019** [comment]
![msedge_IeyHHW0XmA](https://user-images.githubusercontent.com/49812372/184339516-49096616-bc03-4de3-a8e0-d4d601b7ac4e.gif)

**Comment by sps014** [comment]
> @sps014  => I could not get it to display "RED hexagon"?
> 
> How to do  ==> 'background-color': 'red',
> 
> Any suggestion?
> 
> 
> [HTML Source](https://github.com/cytoscape/cytoscape.js-tutorials/blob/master/getting-started/index-layout.html): 
> 
> ```js
> 
> {
>           container: document.getElementById('cy'),
>           elements: [
>             // nodes
>             { data: { id: 'a' } },
>             { data: { id: 'b' } },
>             // edges
>             {
>               data: {
>                 id: 'ab',
>                 source: 'a',
>                 target: 'b'
>               }
>             },
>           ],
>           style: [
>             {
>               selector: 'node',
>               style: {
>                 shape: 'hexagon',
>                 'background-color': 'red',
>                 label: 'data(id)'
>               }
>             }],
>           layout: {
>             name: 'grid'
>           }
>  }
> ```
> ```cs
> 
> 		var param = new Root
> 			{
> 				container = canvas,
> 				elements=new List<Element>
> 				{
> 					new Element{data=new Data{id="a"}},
> 					new Element{data=new Data{id="b"}},
> 					new Element{data=new Data{id="ab",source="a",target="b"}},
> 				},
>                                 style = new List<Style>
>                                {
>                                      new Style{  selector  ="node";  Style = new StyleElement{  shape="hexagon"; label ="data(id)" }  }
>                                }
>                               layout = new Layout{ name="grid" }
> 			};
> /// Elements
>     public class Element
>     {
>         public Data data { get; set; }
>     }
> 
>     public class Data
>     {
>         public string id { get; set; }
>         public string source { get; set; }
>         public string target { get; set; }
>     }
> 
> /// Style
>     public class Style
>     {
>        public string selector  { get; set; }
>         public StyleElement style { get; set; }
>     }
> 
>     public class StyleElement
>     {
>         public string shape{ get; set; }
>         public string label{ get; set; }
>     }
> 
> /// Layout
>     public class Layout
>     {
>         public string name { get; set; }
>     }
> 
>     public class Root
>     {
>         public ElementReference container { get; set; }
>         public List<Element> elements { get; set; }
>         public List<Style> style{ get; set; }
>         public Layout layout { get; set; }
>     }
> ```
> 
> ```
> <style>
>     #cy {
>         width: 400px;
>         height: 400px;
>         position: relative;
>         top: 20px;
>         left: 20px;
>         border: 3px solid #73AD21;
>     }
> </style>
> ```
> 
> ![image](https://user-images.githubusercontent.com/49812372/184249605-430aa090-48c0-4d54-8d78-7689f29b5a79.png)
> 

On higher level you could create a property backgroundColor and annotate it with attribute
```cs [JsonPropertyName("background-color")]
```

**Comment by GeorgeS2019** [comment]
Exactly what I need!

**Comment by GeorgeS2019** [comment]
![image](https://user-images.githubusercontent.com/49812372/184344779-06340b02-a20c-4f71-b460-1545e65b4adc.png)

**Comment by GeorgeS2019** [comment]
```
 let cy = cytoscape({
    container: document.getElementById(containerId),
    elements: [ // list of graph elements to start with
      // empty, is added later
    ],
    style: [ // the stylesheet for the graph
      {
        selector: 'node',
        style: {
          'background-color': '#666',
          'label': 'data(id)'
        }
      },

      {
        selector: 'edge',
        style: {
          'width': 3,
          'line-color': '#ccc',
          'target-arrow-color': '#ccc',
          'target-arrow-shape': 'triangle',
          'curve-style': 'bezier'
        }
      }
    ],

    layout: {
      name: 'grid',
      rows: 1
    }
  });
```

**Comment by sps014** [comment]
on higher level you can print that object and see if correct property names is generated.

**Comment by GeorgeS2019** [comment]
I am attempting to create a BlazorCytoscape in the same way you are sharing https://github.com/sps014/BlazorML5

The main motivation is to provide Bicep Visualization in Blazor

**Comment by GeorgeS2019** [comment]
There is CyJs.NET done in F#  
This support .NET notebook, not yet Blazor

**Comment by sps014** [comment]
Can you share your source code , so i can see what you are doing wrong

**Comment by GeorgeS2019** [comment]
```cs
using Microsoft.AspNetCore.Components;
using Newtonsoft.Json;

namespace Cytoscape.NET.Model
{
    /// Elements
    public class Element
    {
        public Data? data { get; set; }
    }

    public class Data
    {
        public string? id { get; set; }
        public string? source { get; set; }
        public string? target { get; set; }
    }

    // Style
    public class Style
    {
        public string? selector { get; set; }
        public StyleElement? style { get; set; }
    }

 
    public class StyleElement
    {
        public string? shape { get; set; }
        public string? label { get; set; }

        [JsonProperty(PropertyName = "background-color")]
        public string? backgroundColor { get; set; }



        #region Edge
        public int width { get; set; }

        [JsonProperty(PropertyName = "line-color")]
        public string? LineColor { get; set; }

        [JsonProperty(PropertyName = "target-arrow-color")]
        public string? TargetArrowColor { get; set; }

        [JsonProperty(PropertyName = "target-arrow-shape")]
        public string? TargetArrowShape { get; set; }

        [JsonProperty(PropertyName = "curve-style")]
        public string? CurveStyle { get; set; }

        #endregion
    }

    public class Layout
    {
        public string? name { get; set; }
    }

    public class Root
    {
        public ElementReference container { get; set; }
        public List<Element>? elements { get; set; }
        public List<Style>? style { get; set; }
        public Layout? layout { get; set; }
    }

}


var param = new Root
            {
                container = canvas,
                elements = new List<Element>
                    {
                        //nodes
                        new Element{data =new Data{id="a"}},
                        new Element{data=new Data{id="b"}},
                        new Element{data =new Data{id="c"}},
                        new Element{data=new Data{id="d"}},
                        new Element{data=new Data{id="e"}},
                        new Element{data=new Data{id="f"}},
                        //edges
                        new Element{data=new Data{id="ab",source="a",target="b"}},
                        new Element{data=new Data{id="cd",source="c",target="d"}},
                        new Element{data=new Data{id="ef",source="e",target="f"}},
                        new Element{data=new Data{id="ac",source="a",target="c"}},
                        new Element{data=new Data{id="be",source="b",target="e"}},

                        },
                style = new List<Style>
                {
                  new Style{ selector="node", style = new StyleElement{ shape = "hexagon",  backgroundColor ="red" , label="data(id)"}} , 
                  new Style{ selector="edge", style = new StyleElement{ width = 5, LineColor="blue", TargetArrowColor ="green", TargetArrowShape="triangle" , CurveStyle="bezier" } }
                },
                layout = new Layout { name = "random" }

            };

        
        cy = Window.CallRef("cytoscape", param);
```

**Comment by GeorgeS2019** [comment]
I think you could use your existing GraphDraw.razor to check the code
https://github.com/sps014/BlazorBindGen/blob/main/SampleApp/Pages/GraphDraw.razor

**Comment by sps014** [comment]
This is how your object looks like JS side with
```cs
        Window["console"].CallVoid("log", param);
```

![Screenshot 2022-08-13 155437](https://user-images.githubusercontent.com/45932883/184479643-a992c11a-bbca-4b89-a8b4-9595b3e36658.png)

**Comment by sps014** [comment]
This might be related to default value of null being passed in some not assigned properties, I would rather assign a valid default value to begin with.
look in `style[1] background color` is assigned to null and for other's as well.

**Comment by GeorgeS2019** [comment]
![image](https://user-images.githubusercontent.com/49812372/184479800-90d7b176-9670-4b92-b692-bda6f961732a.png)

**Comment by GeorgeS2019** [comment]
Is there a way to specify OptionalVariable so when it is not used, it is ignored?

**Comment by sps014** [comment]
Also you were using `NewtonSoft.Json`use `System.Text.Json` , your property name would look like
```cs
        [JsonPropertyName("background-color")]
```

**Comment by GeorgeS2019** [comment]
Style class in F#

https://github.com/fslaborg/Cyjs.NET/blob/main/src/Cyjs.NET/Style.fs

**Comment by GeorgeS2019** [comment]
@sps014  The F# approach uses DynamicObject,  there is increasing discussion on how to write c# 10 codes that look like Javascript using a more functional approach.

**Comment by GeorgeS2019** [comment]
Found it

 [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]

**Comment by GeorgeS2019** [comment]
![msedge_lahSYjk5ug](https://user-images.githubusercontent.com/49812372/184486581-7bc073a8-a1b0-4a2a-a8bf-963cb381a926.gif)

**Comment by GeorgeS2019** [comment]
@sps014 

I am thinking one step further. 

```js
cy.layout({
    name: 'circle'
}).run();
```

JObjPtr cy = Window.CallRef("cytoscape", param);

cy.CallVoid("layout", "name: 'circle'");

Do you think [I am a right track?](https://blog.js.cytoscape.org/2016/05/24/getting-started/)

**Comment by GeorgeS2019** [comment]
It works but I am getting a lot of error messages
![image](https://user-images.githubusercontent.com/49812372/184490007-b396d83f-dc50-4667-a214-ffffdbf79845.png)

**Comment by GeorgeS2019** [comment]
```
rit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: props[h][fname] is not a function
      TypeError: props[h][fname] is not a function
          at Module.FuncVoid (https://localhost:7257/_content/BlazorBindGen/BlazorBindGen.js:48:20)
          at Object.invokeJSFromDotNet (https://localhost:7257/_framework/blazor.webassembly.js:1:3214)
          at Object.St [as invokeJSFromDotNet] (https://localhost:7257/_framework/blazor.webassembly.js:1:59918)
          at _mono_wasm_invoke_js_blazor (https://localhost:7257/_framework/dotnet.6.0.8.5qvbcwublj.js:1:195300)
          at wasm://wasm/00971db2:wasm-function[219]:0x1a48f
          at wasm://wasm/00971db2:wasm-function[167]:0xce5d
          at wasm://wasm/00971db2:wasm-function[166]:0xbd70
          at wasm://wasm/00971db2:wasm-function[2812]:0xabf00
          at wasm://wasm/00971db2:wasm-function[1616]:0x6fcc1
          at wasm://wasm/00971db2:wasm-function[1620]:0x7032e
Microsoft.JSInterop.JSException: props[h][fname] is not a function
TypeError: props[h][fname] is not a function
    at Module.FuncVoid (https://localhost:7257/_content/BlazorBindGen/BlazorBindGen.js:48:20)
    at Object.invokeJSFromDotNet (https://localhost:7257/_framework/blazor.webassembly.js:1:3214)
    at Object.St [as invokeJSFromDotNet] (https://localhost:7257/_framework/blazor.webassembly.js:1:59918)
    at _mono_wasm_invoke_js_blazor (https://localhost:7257/_framework/dotnet.6.0.8.5qvbcwublj.js:1:195300)
    at wasm://wasm/00971db2:wasm-function[219]:0x1a48f
    at wasm://wasm/00971db2:wasm-function[167]:0xce5d
    at wasm://wasm/00971db2:wasm-function[166]:0xbd70
    at wasm://wasm/00971db2:wasm-function[2812]:0xabf00
    at wasm://wasm/00971db2:wasm-function[1616]:0x6fcc1
    at wasm://wasm/00971db2:wasm-function[1620]:0x7032e
   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeJS(String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
   at Microsoft.JSInterop.JSInProcessRuntime.Invoke[IJSVoidResult](String identifier, Int64 targetInstanceId, Object[] args)
   at Microsoft.JSInterop.Implementation.JSInProcessObjectReference.Invoke[IJSVoidResult](String identifier, Object[] args)
   at Microsoft.JSInterop.JSInProcessObjectReferenceExtensions.InvokeVoid(IJSInProcessObjectReference jsObjectReference, String identifier, Object[] args)
   at BlazorBindGen.JObjPtr.CallVoid(String funcName, Object[] param) in C:\BlazorBindGen\JObjPtr.cs:line 305
   at BlazorWASM1.Pages.GraphDraw.CytoscaleInit() in C:\BlazorWASM1\Pages\GraphDraw.razor:line 88
   at BlazorWASM1.Pages.GraphDraw.OnInitializedAsync() in C:\BlazorWASM1\Pages\GraphDraw.razor:line 30
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

**Comment by sps014** [comment]
```cs
cy.CallVoid("layout", new { name= "circle"});
```

Also make ure `cy` object has a function called `layout` defined as indicated by these errors

**Comment by GeorgeS2019** [comment]
How to format?

cy.CallVoid("style", "node { background-color: cyan; }"); <========work

` cy.CallVoid("style", new { node { shape='hexagon'; background-color='blue', label='data(id)'}});`  <==not work

**Comment by sps014** [comment]
Something like 
```cs
class container
{
    public Node node{get;set;}
}
class Node
{
    [JsonPropertyName("background-color")]
    public  string backgroundColor{get;set;}
    ///.... etc
}
/*create a new instance of container and use constructor or property set */
cy.CallVoid("style", new container());
```

**Comment by GeorgeS2019** [comment]
```js
var stringStylesheet = 'node { background-color: cyan; }';
cy.style( stringStylesheet );
```

Why this works
```cs
cy.CallVoid("style", "node { background-color: cyan; }"); //<========work
```

**Comment by GeorgeS2019** [comment]
```
cy.style()
  .fromString('node { background-color: blue; }')

  .update() // update the elements in the graph with the new style
;
```

Is this possible using your framework??

**Comment by sps014** [comment]
> ```
> cy.style()
>   .fromString('node { background-color: blue; }')
> 
>   .update() // update the elements in the graph with the new style
> ;
> ```
> 
> Is this possible using your framework??

Yes it is

**Comment by GeorgeS2019** [comment]
```cs
cy.CallVoid("style().fromString", "node { background-color: green; }");
cy.CallVoid("update");
```

Not working, something I have done wrong?

**Comment by GeorgeS2019** [comment]
I got it. Thanks

**Comment by sps014** [comment]
> ```cs
> cy.CallVoid("style().fromString", "node { background-color: green; }");
> cy.CallVoid("update");
> ```
> 
> Not working, something I have done wrong?

```cs
cy.CallRef("style").CallRef("fromString","node {}").CallVoid("update");
```

**Comment by GeorgeS2019** [comment]
More superior than I have figure out. Thanky

**Comment by GeorgeS2019** [comment]
```cs
 cy.CallRef("style").CallRef("fromString", "node { background-color: green; }").CallVoid("update");
```
==> I am getting the right result, however, I still get this bunch of error messages

Any suggestion?


```
blazor.webassembly.js:1 
        
       crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: props[h][fname] is not a function
      TypeError: props[h][fname] is not a function
          at Module.FuncVoid (https://localhost:7257/_content/BlazorBindGen/BlazorBindGen.js:48:20)
          at Object.invokeJSFromDotNet (https://localhost:7257/_framework/blazor.webassembly.js:1:3214)
          at Object.St [as invokeJSFromDotNet] (https://localhost:7257/_framework/blazor.webassembly.js:1:59918)
          at _mono_wasm_invoke_js_blazor (https://localhost:7257/_framework/dotnet.6.0.8.5qvbcwublj.js:1:195300)
          at wasm://wasm/00971db2:wasm-function[219]:0x1a48f
          at wasm://wasm/00971db2:wasm-function[167]:0xce5d
          at wasm://wasm/00971db2:wasm-function[166]:0xbd70
          at wasm://wasm/00971db2:wasm-function[2812]:0xabf00
          at wasm://wasm/00971db2:wasm-function[1616]:0x6fcc1
          at wasm://wasm/00971db2:wasm-function[1620]:0x7032e
Microsoft.JSInterop.JSException: props[h][fname] is not a function
TypeError: props[h][fname] is not a function
    at Module.FuncVoid (https://localhost:7257/_content/BlazorBindGen/BlazorBindGen.js:48:20)
    at Object.invokeJSFromDotNet (https://localhost:7257/_framework/blazor.webassembly.js:1:3214)
    at Object.St [as invokeJSFromDotNet] (https://localhost:7257/_framework/blazor.webassembly.js:1:59918)
    at _mono_wasm_invoke_js_blazor (https://localhost:7257/_framework/dotnet.6.0.8.5qvbcwublj.js:1:195300)
    at wasm://wasm/00971db2:wasm-function[219]:0x1a48f
    at wasm://wasm/00971db2:wasm-function[167]:0xce5d
    at wasm://wasm/00971db2:wasm-function[166]:0xbd70
    at wasm://wasm/00971db2:wasm-function[2812]:0xabf00
    at wasm://wasm/00971db2:wasm-function[1616]:0x6fcc1
    at wasm://wasm/00971db2:wasm-function[1620]:0x7032e
   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeJS(String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
   at Microsoft.JSInterop.JSInProcessRuntime.Invoke[IJSVoidResult](String identifier, Int64 targetInstanceId, Object[] args)
   at Microsoft.JSInterop.Implementation.JSInProcessObjectReference.Invoke[IJSVoidResult](String identifier, Object[] args)
   at Microsoft.JSInterop.JSInProcessObjectReferenceExtensions.InvokeVoid(IJSInProcessObjectReference jsObjectReference, String identifier, Object[] args)
   at BlazorBindGen.JObjPtr.CallVoid(String funcName, Object[] param) in C:\BlazorBindGen\JObjPtr.cs:line 305
   at BlazorWASM1.Pages.GraphDraw.CytoscaleInit() in C:\BlazorWASM1\Pages\GraphDraw.razor:line 101
   at BlazorWASM1.Pages.GraphDraw.OnInitializedAsync() in C:\BlazorWASM1\Pages\GraphDraw.razor:line 31
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```
